-- ============================================
-- Unistore: Hybrid Tables for OLTP Workloads
-- ============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CREDIT_DECISIONING_DB;
USE WAREHOUSE TRANSACTIONAL_WH;

-- ============================================
-- HYBRID TABLE: Credit Applications
-- ============================================

CREATE OR REPLACE HYBRID TABLE APP_ZONE.TRANSACTIONAL.CREDIT_APPLICATIONS (
    -- Primary Key
    APPLICATION_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    
    -- Application Details
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    APPLICATION_TYPE VARCHAR(30) NOT NULL,  -- NEW_LOAN, CREDIT_INCREASE, RENEWAL
    PRODUCT_CODE VARCHAR(20) NOT NULL,
    REQUESTED_AMOUNT NUMBER(18,2) NOT NULL,
    REQUESTED_TERM_MONTHS INTEGER,
    PURPOSE VARCHAR(200),
    
    -- Application State
    STATUS VARCHAR(30) DEFAULT 'SUBMITTED',  -- SUBMITTED, IN_REVIEW, PENDING_DOCS, APPROVED, DECLINED, CANCELLED
    CURRENT_STAGE VARCHAR(50) DEFAULT 'INTAKE',
    ASSIGNED_OFFICER VARCHAR(50),
    PRIORITY VARCHAR(20) DEFAULT 'NORMAL',  -- LOW, NORMAL, HIGH, URGENT
    
    -- Timestamps
    SUBMITTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DECISION_DUE_BY TIMESTAMP_NTZ,
    
    -- Locking for concurrent access
    LOCKED_BY VARCHAR(50),
    LOCKED_AT TIMESTAMP_NTZ,
    
    -- Indexes for fast OLTP lookups
    INDEX IDX_CUSTOMER (CUSTOMER_ID),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_OFFICER (ASSIGNED_OFFICER),
    INDEX IDX_SUBMITTED (SUBMITTED_AT)
)
COMMENT = 'Hybrid table for high-throughput credit application processing';

-- ============================================
-- HYBRID TABLE: Credit Decisions
-- ============================================

CREATE OR REPLACE HYBRID TABLE APP_ZONE.TRANSACTIONAL.CREDIT_DECISIONS (
    -- Primary Key
    DECISION_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    APPLICATION_ID VARCHAR(36) NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    
    -- ML Model Output
    ML_SCORE_BAND INTEGER,
    ML_CREDIT_RATING VARCHAR(5),
    ML_RECOMMENDED_DECISION VARCHAR(20),
    ML_MAX_CREDIT_LIMIT NUMBER(18,2),
    ML_MODEL_VERSION VARCHAR(20),
    ML_INFERENCE_TIMESTAMP TIMESTAMP_NTZ,
    
    -- Agent Reasoning
    AGENT_SESSION_ID VARCHAR(36),
    AGENT_ANALYSIS VARIANT,          -- Full agent reasoning JSON
    AGENT_POLICY_CHECKS VARIANT,     -- Which policies were evaluated
    AGENT_RISK_FACTORS VARIANT,      -- Identified risk factors
    AGENT_RECOMMENDATION VARCHAR(20),
    
    -- Final Decision
    FINAL_DECISION VARCHAR(20) NOT NULL,  -- APPROVE, DECLINE, REFER
    APPROVED_AMOUNT NUMBER(18,2),
    APPROVED_TERM_MONTHS INTEGER,
    INTEREST_RATE NUMBER(8,4),
    CONDITIONS VARIANT,              -- Special conditions if any
    DECLINE_REASONS VARIANT,         -- If declined
    
    -- Decision Metadata
    DECISION_TYPE VARCHAR(20),       -- AUTO, AGENT_ASSISTED, MANUAL_OVERRIDE
    DECIDED_BY VARCHAR(100),         -- System, Agent, or Officer ID
    DECISION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Compliance
    FOUR_EYES_REQUIRED BOOLEAN DEFAULT FALSE,
    FOUR_EYES_APPROVED_BY VARCHAR(50),
    FOUR_EYES_TIMESTAMP TIMESTAMP_NTZ,
    
    -- Foreign Key
    FOREIGN KEY (APPLICATION_ID) REFERENCES APP_ZONE.TRANSACTIONAL.CREDIT_APPLICATIONS(APPLICATION_ID),
    
    -- Indexes
    INDEX IDX_APP (APPLICATION_ID),
    INDEX IDX_CUSTOMER_DEC (CUSTOMER_ID),
    INDEX IDX_DECISION_TIME (DECISION_TIMESTAMP)
)
COMMENT = 'Hybrid table for credit decision records with full audit trail';

-- ============================================
-- HYBRID TABLE: Agent Sessions
-- ============================================

CREATE OR REPLACE HYBRID TABLE APP_ZONE.TRANSACTIONAL.AGENT_SESSIONS (
    -- Primary Key
    SESSION_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    APPLICATION_ID VARCHAR(36),
    CUSTOMER_ID VARCHAR(20),
    USER_ID VARCHAR(50) NOT NULL,
    USER_ROLE VARCHAR(50),           -- CREDIT_OFFICER, RISK_MANAGER, etc.
    
    -- Session State
    SESSION_STATUS VARCHAR(20) DEFAULT 'ACTIVE',  -- ACTIVE, COMPLETED, ABANDONED
    STARTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_ACTIVITY_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ENDED_AT TIMESTAMP_NTZ,
    
    -- Conversation
    MESSAGE_COUNT INTEGER DEFAULT 0,
    MESSAGES VARIANT,                -- Array of messages
    
    -- Context
    POLICIES_REFERENCED VARIANT,     -- Which policies were looked up
    DATA_ACCESSED VARIANT,           -- What customer data was accessed
    TOOLS_USED VARIANT,              -- ML model, search, etc.
    
    -- Outcome
    DECISION_MADE BOOLEAN DEFAULT FALSE,
    DECISION_ID VARCHAR(36),
    
    -- Indexes
    INDEX IDX_APP_SESSION (APPLICATION_ID),
    INDEX IDX_USER_SESSION (USER_ID),
    INDEX IDX_STATUS_SESSION (SESSION_STATUS)
)
COMMENT = 'Hybrid table for tracking AI agent conversation sessions';

-- ============================================
-- VIEW: Application Queue
-- ============================================

CREATE OR REPLACE VIEW APP_ZONE.TRANSACTIONAL.V_APPLICATION_QUEUE AS
SELECT 
    a.APPLICATION_ID,
    a.CUSTOMER_ID,
    c.FULL_NAME AS CUSTOMER_NAME,
    a.APPLICATION_TYPE,
    a.PRODUCT_CODE,
    a.REQUESTED_AMOUNT,
    a.STATUS,
    a.CURRENT_STAGE,
    a.PRIORITY,
    a.ASSIGNED_OFFICER,
    a.SUBMITTED_AT,
    a.DECISION_DUE_BY,
    DATEDIFF('HOUR', a.SUBMITTED_AT, CURRENT_TIMESTAMP()) AS HOURS_IN_QUEUE,
    CASE 
        WHEN a.DECISION_DUE_BY < CURRENT_TIMESTAMP() THEN 'OVERDUE'
        WHEN a.DECISION_DUE_BY < DATEADD('HOUR', 4, CURRENT_TIMESTAMP()) THEN 'DUE_SOON'
        ELSE 'ON_TRACK'
    END AS SLA_STATUS,
    c.CREDIT_SCORE,
    c.RISK_CATEGORY,
    c.TOTAL_DEPOSITS,
    c.TOTAL_LOANS_OUTSTANDING
FROM APP_ZONE.TRANSACTIONAL.CREDIT_APPLICATIONS a
LEFT JOIN ANALYTICS_ZONE.CUSTOMER_360.CUSTOMER_360_UNIFIED c 
    ON a.CUSTOMER_ID = c.CUSTOMER_ID
WHERE a.STATUS NOT IN ('APPROVED', 'DECLINED', 'CANCELLED')
ORDER BY 
    CASE a.PRIORITY 
        WHEN 'URGENT' THEN 1 
        WHEN 'HIGH' THEN 2 
        WHEN 'NORMAL' THEN 3 
        ELSE 4 
    END,
    a.SUBMITTED_AT;

SELECT 
    'Hybrid tables created successfully' AS STATUS,
    'Ready for high-performance OLTP workloads' AS READY_STATE;

-- Show table details
SELECT 
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    IS_HYBRID
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'TRANSACTIONAL'
AND TABLE_TYPE = 'BASE TABLE';
