-- ============================================
-- Data Classification Tags
-- ============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CREDIT_DECISIONING_DB;
USE WAREHOUSE ETL_WH;

-- ============================================
-- CREATE CLASSIFICATION TAGS
-- ============================================

-- Data Sensitivity Tag
CREATE OR REPLACE TAG GOVERNANCE.TAGS.DATA_SENSITIVITY
  ALLOWED_VALUES = ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', 'PII')
  COMMENT = 'Data sensitivity classification level';

-- PII Type Tag
CREATE OR REPLACE TAG GOVERNANCE.TAGS.PII_TYPE
  ALLOWED_VALUES = ('NAME', 'EMAIL', 'PHONE', 'SSN', 'DOB', 'ADDRESS', 'ACCOUNT_NUMBER', 'INCOME', 'NONE')
  COMMENT = 'Type of personally identifiable information';

-- Data Domain Tag
CREATE OR REPLACE TAG GOVERNANCE.TAGS.DATA_DOMAIN
  ALLOWED_VALUES = ('CUSTOMER', 'ACCOUNT', 'TRANSACTION', 'CREDIT', 'DIGITAL', 'FRAUD', 'REFERENCE')
  COMMENT = 'Business domain classification';

-- Data Source Tag
CREATE OR REPLACE TAG GOVERNANCE.TAGS.DATA_SOURCE
  ALLOWED_VALUES = ('T24_ORACLE', 'MYSQL_DIGITAL', 'DATABRICKS_BUREAU', 'SNOWFLAKE_DERIVED', 'EXTERNAL')
  COMMENT = 'Origin system for data lineage tracking';

-- ============================================
-- APPLY TAGS TO CUSTOMER 360 TABLE
-- ============================================

-- Full Name - PII
ALTER TABLE ANALYTICS_ZONE.CUSTOMER_360.CUSTOMER_360_UNIFIED 
  MODIFY COLUMN FULL_NAME 
  SET TAG GOVERNANCE.TAGS.PII_TYPE = 'NAME',
      GOVERNANCE.TAGS.DATA_SENSITIVITY = 'PII';

-- Date of Birth - PII
ALTER TABLE ANALYTICS_ZONE.CUSTOMER_360.CUSTOMER_360_UNIFIED 
  MODIFY COLUMN DATE_OF_BIRTH 
  SET TAG GOVERNANCE.TAGS.PII_TYPE = 'DOB',
      GOVERNANCE.TAGS.DATA_SENSITIVITY = 'PII';

-- Income - Confidential
ALTER TABLE ANALYTICS_ZONE.CUSTOMER_360.CUSTOMER_360_UNIFIED 
  MODIFY COLUMN VERIFIED_ANNUAL_INCOME 
  SET TAG GOVERNANCE.TAGS.PII_TYPE = 'INCOME',
      GOVERNANCE.TAGS.DATA_SENSITIVITY = 'CONFIDENTIAL';

-- Customer ID - Internal
ALTER TABLE ANALYTICS_ZONE.CUSTOMER_360.CUSTOMER_360_UNIFIED 
  MODIFY COLUMN CUSTOMER_ID 
  SET TAG GOVERNANCE.TAGS.DATA_SENSITIVITY = 'INTERNAL';

-- Table-level tags
ALTER TABLE ANALYTICS_ZONE.CUSTOMER_360.CUSTOMER_360_UNIFIED 
  SET TAG GOVERNANCE.TAGS.DATA_DOMAIN = 'CUSTOMER',
      GOVERNANCE.TAGS.DATA_SOURCE = 'SNOWFLAKE_DERIVED';

-- ============================================
-- APPLY TAGS TO TRANSACTION DATA
-- ============================================

ALTER TABLE CURATED_ZONE.TRANSACTIONS.FACT_TRANSACTIONS
  SET TAG GOVERNANCE.TAGS.DATA_DOMAIN = 'TRANSACTION',
      GOVERNANCE.TAGS.DATA_SOURCE = 'T24_ORACLE',
      GOVERNANCE.TAGS.DATA_SENSITIVITY = 'CONFIDENTIAL';

-- ============================================
-- VIEW TAG ASSIGNMENTS
-- ============================================

-- Query to see all tag assignments
SELECT 
    TAG_DATABASE,
    TAG_SCHEMA,
    TAG_NAME,
    COLUMN_NAME,
    TAG_VALUE,
    OBJECT_DATABASE,
    OBJECT_SCHEMA,
    OBJECT_NAME,
    DOMAIN AS OBJECT_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE TAG_DATABASE = 'CREDIT_DECISIONING_DB'
ORDER BY OBJECT_NAME, COLUMN_NAME;

SELECT 'Data classification tags created and applied successfully' AS STATUS;
