-- ============================================
-- Oracle T24 Database Initialization
-- ============================================

-- Create T24 tables
CREATE TABLE T24_CUSTOMER (
    CUSTOMER_ID VARCHAR2(20) PRIMARY KEY,
    MNEMONIC VARCHAR2(50),
    SHORT_NAME VARCHAR2(100),
    NAME_1 VARCHAR2(100),
    NAME_2 VARCHAR2(100),
    GENDER VARCHAR2(10),
    DATE_OF_BIRTH DATE,
    MARITAL_STATUS VARCHAR2(20),
    NATIONALITY VARCHAR2(3),
    RESIDENCE VARCHAR2(3),
    SECTOR VARCHAR2(10),
    INDUSTRY VARCHAR2(10),
    TARGET_MARKET VARCHAR2(20),
    CUSTOMER_STATUS VARCHAR2(20),
    CUSTOMER_SINCE DATE,
    KYC_STATUS VARCHAR2(20),
    KYC_LAST_REVIEW DATE,
    RISK_CATEGORY VARCHAR2(20),
    RELATIONSHIP_MANAGER VARCHAR2(50),
    BRANCH_CODE VARCHAR2(10),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE T24_ACCOUNT (
    ACCOUNT_ID VARCHAR2(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(20),
    ACCOUNT_TITLE VARCHAR2(100),
    CATEGORY VARCHAR2(10),
    PRODUCT_CODE VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(100),
    CURRENCY VARCHAR2(3),
    WORKING_BALANCE NUMBER(18,2),
    ONLINE_ACTUAL_BAL NUMBER(18,2),
    LOCKED_AMOUNT NUMBER(18,2),
    AVAILABLE_LIMIT NUMBER(18,2),
    ACCOUNT_STATUS VARCHAR2(20),
    OPENING_DATE DATE,
    LAST_ACTIVITY_DATE DATE,
    INTEREST_RATE NUMBER(8,4),
    BRANCH_CODE VARCHAR2(10),
    JOINT_HOLDER_1 VARCHAR2(20),
    JOINT_HOLDER_2 VARCHAR2(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES T24_CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE T24_LOAN (
    LOAN_ID VARCHAR2(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(20),
    ACCOUNT_ID VARCHAR2(20),
    LOAN_TYPE VARCHAR2(30),
    PRODUCT_CODE VARCHAR2(20),
    PRODUCT_NAME VARCHAR2(100),
    CURRENCY VARCHAR2(3),
    PRINCIPAL_AMOUNT NUMBER(18,2),
    OUTSTANDING_PRINCIPAL NUMBER(18,2),
    INTEREST_RATE NUMBER(8,4),
    INTEREST_TYPE VARCHAR2(20),
    TERM_MONTHS INTEGER,
    MONTHLY_PAYMENT NUMBER(18,2),
    START_DATE DATE,
    MATURITY_DATE DATE,
    NEXT_PAYMENT_DATE DATE,
    PAYMENTS_MADE INTEGER,
    PAYMENTS_REMAINING INTEGER,
    DAYS_PAST_DUE INTEGER,
    ARREARS_AMOUNT NUMBER(18,2),
    LOAN_STATUS VARCHAR2(20),
    COLLATERAL_TYPE VARCHAR2(30),
    COLLATERAL_VALUE NUMBER(18,2),
    LTV_RATIO NUMBER(8,4),
    APPROVAL_DATE DATE,
    APPROVED_BY VARCHAR2(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES T24_CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE T24_TRANSACTION (
    TRANSACTION_ID VARCHAR2(30) PRIMARY KEY,
    ACCOUNT_ID VARCHAR2(20),
    CUSTOMER_ID VARCHAR2(20),
    TRANSACTION_TYPE VARCHAR2(30),
    TRANSACTION_CODE VARCHAR2(10),
    TRANSACTION_DESC VARCHAR2(200),
    AMOUNT NUMBER(18,2),
    CURRENCY VARCHAR2(3),
    AMOUNT_LCY NUMBER(18,2),
    EXCHANGE_RATE NUMBER(12,6),
    VALUE_DATE DATE,
    BOOKING_DATE DATE,
    PROCESSING_TIME TIMESTAMP,
    BALANCE_AFTER NUMBER(18,2),
    CHANNEL VARCHAR2(30),
    MERCHANT_NAME VARCHAR2(100),
    MERCHANT_CATEGORY VARCHAR2(50),
    COUNTERPARTY_ACCT VARCHAR2(30),
    COUNTERPARTY_NAME VARCHAR2(100),
    COUNTERPARTY_BANK VARCHAR2(100),
    REFERENCE VARCHAR2(50),
    REVERSAL_FLAG NUMBER(1),
    REVERSED_TXN_ID VARCHAR2(30),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE T24_PAYMENT_SCHEDULE (
    SCHEDULE_ID VARCHAR2(30) PRIMARY KEY,
    LOAN_ID VARCHAR2(20),
    CUSTOMER_ID VARCHAR2(20),
    INSTALLMENT_NUMBER INTEGER,
    DUE_DATE DATE,
    PRINCIPAL_DUE NUMBER(18,2),
    INTEREST_DUE NUMBER(18,2),
    TOTAL_DUE NUMBER(18,2),
    PRINCIPAL_PAID NUMBER(18,2),
    INTEREST_PAID NUMBER(18,2),
    TOTAL_PAID NUMBER(18,2),
    PAYMENT_DATE DATE,
    PAYMENT_STATUS VARCHAR2(20),
    DAYS_LATE INTEGER,
    PENALTY_AMOUNT NUMBER(18,2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LOAN_ID) REFERENCES T24_LOAN(LOAN_ID)
);

CREATE TABLE T24_COLLATERAL (
    COLLATERAL_ID VARCHAR2(20) PRIMARY KEY,
    LOAN_ID VARCHAR2(20),
    CUSTOMER_ID VARCHAR2(20),
    COLLATERAL_TYPE VARCHAR2(30),
    DESCRIPTION VARCHAR2(500),
    ORIGINAL_VALUE NUMBER(18,2),
    CURRENT_VALUE NUMBER(18,2),
    VALUATION_DATE DATE,
    VALUATION_SOURCE VARCHAR2(100),
    CURRENCY VARCHAR2(3),
    LOCATION VARCHAR2(200),
    INSURANCE_POLICY VARCHAR2(50),
    INSURANCE_EXPIRY DATE,
    LIEN_POSITION INTEGER,
    REGISTRATION_REF VARCHAR2(50),
    STATUS VARCHAR2(20),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LOAN_ID) REFERENCES T24_LOAN(LOAN_ID)
);

-- Create indexes for performance
CREATE INDEX IDX_T24_ACCOUNT_CUSTOMER ON T24_ACCOUNT(CUSTOMER_ID);
CREATE INDEX IDX_T24_LOAN_CUSTOMER ON T24_LOAN(CUSTOMER_ID);
CREATE INDEX IDX_T24_TRANSACTION_ACCOUNT ON T24_TRANSACTION(ACCOUNT_ID);
CREATE INDEX IDX_T24_TRANSACTION_DATE ON T24_TRANSACTION(VALUE_DATE);

COMMIT;
