-- ============================================
-- Snowflake Credit Decisioning Platform
-- Direct Load: Create All Tables
-- ============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CREDIT_DECISIONING_DB;

-- ============================================
-- DIGITAL BANKING SCHEMA (4 tables)
-- ============================================

USE SCHEMA DIGITAL_BANKING;

CREATE OR REPLACE TABLE DIGITAL_CUSTOMER_PROFILE (
    DIGITAL_ID VARCHAR(36) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    EMAIL VARCHAR(100),
    MOBILE_NUMBER VARCHAR(20),
    USERNAME VARCHAR(50),
    REGISTRATION_DATE TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    LOGIN_COUNT INTEGER,
    FAILED_LOGIN_COUNT INTEGER,
    MFA_ENABLED BOOLEAN,
    MFA_TYPE VARCHAR(20),
    DEVICE_COUNT INTEGER,
    PRIMARY_DEVICE_TYPE VARCHAR(20),
    BIOMETRIC_ENABLED BOOLEAN,
    PUSH_NOTIFICATIONS BOOLEAN,
    EMAIL_VERIFIED BOOLEAN,
    MOBILE_VERIFIED BOOLEAN,
    EKYC_STATUS VARCHAR(20),
    EKYC_DATE TIMESTAMP,
    PREFERRED_LANGUAGE VARCHAR(10),
    TIMEZONE VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE DIGITAL_SESSION (
    SESSION_ID VARCHAR(36) PRIMARY KEY,
    DIGITAL_ID VARCHAR(36),
    CUSTOMER_ID VARCHAR(20),
    SESSION_START TIMESTAMP,
    SESSION_END TIMESTAMP,
    DURATION_SECONDS INTEGER,
    DEVICE_ID VARCHAR(100),
    DEVICE_TYPE VARCHAR(20),
    DEVICE_MODEL VARCHAR(50),
    OS_VERSION VARCHAR(20),
    APP_VERSION VARCHAR(20),
    IP_ADDRESS VARCHAR(45),
    GEOLOCATION_LAT DECIMAL(10,7),
    GEOLOCATION_LON DECIMAL(10,7),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(3),
    PAGES_VIEWED INTEGER,
    TRANSACTIONS_INITIATED INTEGER,
    TRANSACTIONS_COMPLETED INTEGER,
    ERROR_COUNT INTEGER,
    SESSION_QUALITY_SCORE DECIMAL(5,2),
    EXIT_REASON VARCHAR(30),
    CREATED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE DIGITAL_EVENT (
    EVENT_ID VARCHAR(36) PRIMARY KEY,
    SESSION_ID VARCHAR(36),
    DIGITAL_ID VARCHAR(36),
    CUSTOMER_ID VARCHAR(20),
    EVENT_TYPE VARCHAR(50),
    EVENT_NAME VARCHAR(100),
    EVENT_TIMESTAMP TIMESTAMP,
    PAGE_NAME VARCHAR(100),
    ELEMENT_ID VARCHAR(100),
    EVENT_DATA VARCHAR(5000),
    RESPONSE_TIME_MS INTEGER,
    SUCCESS BOOLEAN,
    ERROR_CODE VARCHAR(20),
    ERROR_MESSAGE VARCHAR(500),
    CREATED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE DIGITAL_KYC_DOCUMENT (
    DOCUMENT_ID VARCHAR(36) PRIMARY KEY,
    DIGITAL_ID VARCHAR(36),
    CUSTOMER_ID VARCHAR(20),
    DOCUMENT_TYPE VARCHAR(30),
    DOCUMENT_NUMBER VARCHAR(50),
    ISSUING_COUNTRY VARCHAR(3),
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    UPLOAD_DATE TIMESTAMP,
    VERIFICATION_STATUS VARCHAR(20),
    VERIFICATION_DATE TIMESTAMP,
    VERIFICATION_METHOD VARCHAR(30),
    CONFIDENCE_SCORE DECIMAL(5,2),
    REJECTION_REASON VARCHAR(200),
    FACE_MATCH_SCORE DECIMAL(5,2),
    LIVENESS_CHECK BOOLEAN,
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP
);

-- ============================================
-- CORE BANKING SCHEMA (6 tables)
-- ============================================

USE SCHEMA CORE_BANKING;

CREATE OR REPLACE TABLE T24_CUSTOMER (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    MNEMONIC VARCHAR(50),
    SHORT_NAME VARCHAR(100),
    NAME_1 VARCHAR(100),
    NAME_2 VARCHAR(100),
    GENDER VARCHAR(10),
    DATE_OF_BIRTH DATE,
    MARITAL_STATUS VARCHAR(20),
    NATIONALITY VARCHAR(3),
    RESIDENCE VARCHAR(3),
    SECTOR VARCHAR(10),
    INDUSTRY VARCHAR(10),
    TARGET_MARKET VARCHAR(20),
    CUSTOMER_STATUS VARCHAR(20),
    CUSTOMER_SINCE DATE,
    KYC_STATUS VARCHAR(20),
    KYC_LAST_REVIEW DATE,
    RISK_CATEGORY VARCHAR(20),
    RELATIONSHIP_MANAGER VARCHAR(50),
    BRANCH_CODE VARCHAR(10),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE T24_ACCOUNT (
    ACCOUNT_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    ACCOUNT_TITLE VARCHAR(100),
    CATEGORY VARCHAR(10),
    PRODUCT_CODE VARCHAR(20),
    PRODUCT_NAME VARCHAR(100),
    CURRENCY VARCHAR(3),
    WORKING_BALANCE DECIMAL(18,2),
    ONLINE_ACTUAL_BAL DECIMAL(18,2),
    LOCKED_AMOUNT DECIMAL(18,2),
    AVAILABLE_LIMIT DECIMAL(18,2),
    ACCOUNT_STATUS VARCHAR(20),
    OPENING_DATE DATE,
    LAST_ACTIVITY_DATE DATE,
    INTEREST_RATE DECIMAL(8,4),
    BRANCH_CODE VARCHAR(10),
    JOINT_HOLDER_1 VARCHAR(20),
    JOINT_HOLDER_2 VARCHAR(20),
    CREATED_DATE DATE,
    MODIFIED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE T24_LOAN (
    LOAN_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    ACCOUNT_ID VARCHAR(20),
    LOAN_TYPE VARCHAR(30),
    PRODUCT_CODE VARCHAR(20),
    PRODUCT_NAME VARCHAR(100),
    CURRENCY VARCHAR(3),
    PRINCIPAL_AMOUNT DECIMAL(18,2),
    OUTSTANDING_PRINCIPAL DECIMAL(18,2),
    INTEREST_RATE DECIMAL(8,4),
    INTEREST_TYPE VARCHAR(20),
    TERM_MONTHS INTEGER,
    MONTHLY_PAYMENT DECIMAL(18,2),
    START_DATE DATE,
    MATURITY_DATE DATE,
    NEXT_PAYMENT_DATE DATE,
    PAYMENTS_MADE INTEGER,
    PAYMENTS_REMAINING INTEGER,
    DAYS_PAST_DUE INTEGER,
    ARREARS_AMOUNT DECIMAL(18,2),
    LOAN_STATUS VARCHAR(20),
    COLLATERAL_TYPE VARCHAR(30),
    COLLATERAL_VALUE DECIMAL(18,2),
    LTV_RATIO DECIMAL(8,4),
    APPROVAL_DATE DATE,
    APPROVED_BY VARCHAR(50),
    CREATED_DATE DATE,
    MODIFIED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE T24_TRANSACTION (
    TRANSACTION_ID VARCHAR(30) PRIMARY KEY,
    ACCOUNT_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    TRANSACTION_TYPE VARCHAR(30),
    TRANSACTION_CODE VARCHAR(10),
    TRANSACTION_DESC VARCHAR(200),
    AMOUNT DECIMAL(18,2),
    CURRENCY VARCHAR(3),
    AMOUNT_LCY DECIMAL(18,2),
    EXCHANGE_RATE DECIMAL(12,6),
    VALUE_DATE DATE,
    BOOKING_DATE DATE,
    PROCESSING_TIME TIMESTAMP,
    BALANCE_AFTER DECIMAL(18,2),
    CHANNEL VARCHAR(30),
    MERCHANT_NAME VARCHAR(100),
    MERCHANT_CATEGORY VARCHAR(50),
    COUNTERPARTY_ACCT VARCHAR(30),
    COUNTERPARTY_NAME VARCHAR(100),
    COUNTERPARTY_BANK VARCHAR(100),
    REFERENCE VARCHAR(50),
    REVERSAL_FLAG INTEGER,
    REVERSED_TXN_ID VARCHAR(30),
    CREATED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE T24_PAYMENT_SCHEDULE (
    SCHEDULE_ID VARCHAR(30) PRIMARY KEY,
    LOAN_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    INSTALLMENT_NUMBER INTEGER,
    DUE_DATE DATE,
    PRINCIPAL_DUE DECIMAL(18,2),
    INTEREST_DUE DECIMAL(18,2),
    TOTAL_DUE DECIMAL(18,2),
    PRINCIPAL_PAID DECIMAL(18,2),
    INTEREST_PAID DECIMAL(18,2),
    TOTAL_PAID DECIMAL(18,2),
    PAYMENT_DATE DATE,
    PAYMENT_STATUS VARCHAR(20),
    DAYS_LATE INTEGER,
    PENALTY_AMOUNT DECIMAL(18,2),
    CREATED_DATE DATE,
    MODIFIED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE T24_COLLATERAL (
    COLLATERAL_ID VARCHAR(20) PRIMARY KEY,
    LOAN_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    COLLATERAL_TYPE VARCHAR(30),
    DESCRIPTION VARCHAR(500),
    ORIGINAL_VALUE DECIMAL(18,2),
    CURRENT_VALUE DECIMAL(18,2),
    VALUATION_DATE DATE,
    VALUATION_SOURCE VARCHAR(100),
    CURRENCY VARCHAR(3),
    LOCATION VARCHAR(200),
    INSURANCE_POLICY VARCHAR(50),
    INSURANCE_EXPIRY DATE,
    LIEN_POSITION INTEGER,
    REGISTRATION_REF VARCHAR(50),
    STATUS VARCHAR(20),
    CREATED_DATE DATE,
    MODIFIED_DATE TIMESTAMP
);

-- ============================================
-- CREDIT BUREAU SCHEMA (4 tables)
-- ============================================

USE SCHEMA CREDIT_BUREAU;

CREATE OR REPLACE TABLE CREDIT_SCORE (
    CREDIT_SCORE_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    BUREAU_NAME VARCHAR(50),
    SCORE INTEGER,
    SCORE_DATE DATE,
    SCORE_VERSION VARCHAR(10),
    DELINQUENCY_SCORE INTEGER,
    BANKRUPTCY_FLAG INTEGER,
    FORECLOSURE_FLAG INTEGER,
    TOTAL_ACCOUNTS INTEGER,
    OPEN_ACCOUNTS INTEGER,
    TOTAL_BALANCE DECIMAL(18,2),
    AVAILABLE_CREDIT DECIMAL(18,2),
    CREDIT_UTILIZATION DECIMAL(5,2),
    OLDEST_ACCOUNT_MONTHS INTEGER,
    RECENT_INQUIRIES INTEGER,
    DEROGATORY_MARKS INTEGER,
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE CREDIT_INQUIRY (
    INQUIRY_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    INQUIRY_DATE DATE,
    INQUIRY_TYPE VARCHAR(10),
    CREDITOR_NAME VARCHAR(100),
    PRODUCT_TYPE VARCHAR(30),
    INQUIRY_AMOUNT DECIMAL(18,2),
    INQUIRY_REASON VARCHAR(50),
    CREATED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE TRADELINE (
    TRADELINE_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    CREDITOR_NAME VARCHAR(100),
    ACCOUNT_TYPE VARCHAR(30),
    ACCOUNT_NUMBER VARCHAR(20),
    ACCOUNT_STATUS VARCHAR(20),
    OPEN_DATE DATE,
    CLOSE_DATE DATE,
    CREDIT_LIMIT DECIMAL(18,2),
    CURRENT_BALANCE DECIMAL(18,2),
    HIGHEST_BALANCE DECIMAL(18,2),
    PAYMENT_STATUS VARCHAR(20),
    MONTHLY_PAYMENT DECIMAL(18,2),
    LAST_PAYMENT_DATE DATE,
    LAST_PAYMENT_AMOUNT DECIMAL(18,2),
    CREATED_DATE DATE,
    MODIFIED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE PUBLIC_RECORD (
    RECORD_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20),
    RECORD_TYPE VARCHAR(30),
    FILING_DATE DATE,
    CLOSE_DATE DATE,
    STATUS VARCHAR(20),
    AMOUNT DECIMAL(18,2),
    COURT VARCHAR(100),
    CASE_NUMBER VARCHAR(50),
    CREATED_DATE DATE,
    MODIFIED_DATE TIMESTAMP
);

-- ============================================
-- REFERENCE DATA SCHEMA (5 tables)
-- ============================================

USE SCHEMA REFERENCE_DATA;

CREATE OR REPLACE TABLE COUNTRY_CODE (
    COUNTRY_CODE VARCHAR(3) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100),
    ISO2_CODE VARCHAR(2),
    REGION VARCHAR(50),
    CURRENCY VARCHAR(3),
    ACTIVE BOOLEAN,
    CREATED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE CURRENCY_CODE (
    CURRENCY_CODE VARCHAR(3) PRIMARY KEY,
    CURRENCY_NAME VARCHAR(100),
    SYMBOL VARCHAR(10),
    DECIMAL_PLACES INTEGER,
    ACTIVE BOOLEAN,
    CREATED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE PRODUCT_CATALOG (
    PRODUCT_CODE VARCHAR(20) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    PRODUCT_CATEGORY VARCHAR(30),
    INTEREST_RATE DECIMAL(8,4),
    MIN_AMOUNT DECIMAL(18,2),
    MAX_AMOUNT DECIMAL(18,2),
    ACTIVE BOOLEAN,
    DESCRIPTION VARCHAR(500),
    CREATED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE BRANCH_DIRECTORY (
    BRANCH_CODE VARCHAR(10) PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(3),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    MANAGER VARCHAR(100),
    OPENED_DATE DATE,
    ACTIVE BOOLEAN,
    CREATED_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE RELATIONSHIP_MANAGER (
    RM_CODE VARCHAR(10) PRIMARY KEY,
    RM_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    BRANCH_CODE VARCHAR(10),
    SPECIALIZATION VARCHAR(30),
    ACTIVE_CUSTOMERS INTEGER,
    PORTFOLIO_VALUE DECIMAL(18,2),
    HIRE_DATE DATE,
    ACTIVE BOOLEAN,
    CREATED_DATE TIMESTAMP
);

-- ============================================
-- NOTE: Snowflake regular tables use automatic micro-partitioning
-- No explicit indexes needed - pruning is automatic!
-- ============================================

SELECT 'All tables created successfully' AS STATUS;
