-- ============================================
-- Snowflake Credit Decisioning Platform
-- COMPLETE DATA LOAD SCRIPT
-- ============================================
-- Run this after uploading CSV files to @PUBLIC.CSV_DATA_STAGE

USE ROLE ACCOUNTADMIN;
USE DATABASE CREDIT_DECISIONING_DB;
USE WAREHOUSE COMPUTE_WH;

-- ============================================
-- DIGITAL_BANKING SCHEMA - 4 tables
-- ============================================

USE SCHEMA DIGITAL_BANKING;

TRUNCATE TABLE DIGITAL_CUSTOMER_PROFILE;
COPY INTO DIGITAL_CUSTOMER_PROFILE 
FROM @PUBLIC.CSV_DATA_STAGE/digital_customer_profile.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE DIGITAL_SESSION;
COPY INTO DIGITAL_SESSION 
FROM @PUBLIC.CSV_DATA_STAGE/digital_session.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE DIGITAL_EVENT;
COPY INTO DIGITAL_EVENT 
FROM @PUBLIC.CSV_DATA_STAGE/digital_event.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE DIGITAL_KYC_DOCUMENT;
COPY INTO DIGITAL_KYC_DOCUMENT 
FROM @PUBLIC.CSV_DATA_STAGE/digital_kyc_document.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

-- Validate Digital Banking
SELECT 'DIGITAL_CUSTOMER_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIGITAL_CUSTOMER_PROFILE
UNION ALL
SELECT 'DIGITAL_SESSION', COUNT(*) FROM DIGITAL_SESSION
UNION ALL
SELECT 'DIGITAL_EVENT', COUNT(*) FROM DIGITAL_EVENT
UNION ALL
SELECT 'DIGITAL_KYC_DOCUMENT', COUNT(*) FROM DIGITAL_KYC_DOCUMENT;

-- ============================================
-- CORE_BANKING SCHEMA - 6 tables
-- ============================================

USE SCHEMA CORE_BANKING;

TRUNCATE TABLE T24_CUSTOMER;
COPY INTO T24_CUSTOMER 
FROM @PUBLIC.CSV_DATA_STAGE/t24_customer.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE T24_ACCOUNT;
COPY INTO T24_ACCOUNT 
FROM @PUBLIC.CSV_DATA_STAGE/t24_account.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE T24_LOAN;
COPY INTO T24_LOAN 
FROM @PUBLIC.CSV_DATA_STAGE/t24_loan.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE T24_TRANSACTION;
COPY INTO T24_TRANSACTION 
FROM @PUBLIC.CSV_DATA_STAGE/t24_transaction.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE T24_PAYMENT_SCHEDULE;
COPY INTO T24_PAYMENT_SCHEDULE 
FROM @PUBLIC.CSV_DATA_STAGE/t24_payment_schedule.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE T24_COLLATERAL;
COPY INTO T24_COLLATERAL 
FROM @PUBLIC.CSV_DATA_STAGE/t24_collateral.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

-- Validate Core Banking
SELECT 'T24_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM T24_CUSTOMER
UNION ALL
SELECT 'T24_ACCOUNT', COUNT(*) FROM T24_ACCOUNT
UNION ALL
SELECT 'T24_LOAN', COUNT(*) FROM T24_LOAN
UNION ALL
SELECT 'T24_TRANSACTION', COUNT(*) FROM T24_TRANSACTION
UNION ALL
SELECT 'T24_PAYMENT_SCHEDULE', COUNT(*) FROM T24_PAYMENT_SCHEDULE
UNION ALL
SELECT 'T24_COLLATERAL', COUNT(*) FROM T24_COLLATERAL;

-- ============================================
-- CREDIT_BUREAU SCHEMA - 4 tables
-- ============================================

USE SCHEMA CREDIT_BUREAU;

TRUNCATE TABLE CREDIT_SCORE;
COPY INTO CREDIT_SCORE 
FROM @PUBLIC.CSV_DATA_STAGE/credit_score.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE CREDIT_INQUIRY;
COPY INTO CREDIT_INQUIRY 
FROM @PUBLIC.CSV_DATA_STAGE/credit_inquiry.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE TRADELINE;
COPY INTO TRADELINE 
FROM @PUBLIC.CSV_DATA_STAGE/tradeline.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE PUBLIC_RECORD;
COPY INTO PUBLIC_RECORD 
FROM @PUBLIC.CSV_DATA_STAGE/public_record.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

-- Validate Credit Bureau
SELECT 'CREDIT_SCORE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CREDIT_SCORE
UNION ALL
SELECT 'CREDIT_INQUIRY', COUNT(*) FROM CREDIT_INQUIRY
UNION ALL
SELECT 'TRADELINE', COUNT(*) FROM TRADELINE
UNION ALL
SELECT 'PUBLIC_RECORD', COUNT(*) FROM PUBLIC_RECORD;

-- ============================================
-- REFERENCE_DATA SCHEMA - 5 tables
-- ============================================

USE SCHEMA REFERENCE_DATA;

TRUNCATE TABLE COUNTRY_CODE;
COPY INTO COUNTRY_CODE 
FROM @PUBLIC.CSV_DATA_STAGE/country_code.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE CURRENCY_CODE;
COPY INTO CURRENCY_CODE 
FROM @PUBLIC.CSV_DATA_STAGE/currency_code.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE PRODUCT_CATALOG;
COPY INTO PRODUCT_CATALOG 
FROM @PUBLIC.CSV_DATA_STAGE/product_catalog.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE BRANCH_DIRECTORY;
COPY INTO BRANCH_DIRECTORY 
FROM @PUBLIC.CSV_DATA_STAGE/branch_directory.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

TRUNCATE TABLE RELATIONSHIP_MANAGER;
COPY INTO RELATIONSHIP_MANAGER 
FROM @PUBLIC.CSV_DATA_STAGE/relationship_manager.csv
FILE_FORMAT = (
    TYPE='CSV' 
    SKIP_HEADER=1 
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
)
ON_ERROR = 'CONTINUE';

-- Validate Reference Data
SELECT 'COUNTRY_CODE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM COUNTRY_CODE
UNION ALL
SELECT 'CURRENCY_CODE', COUNT(*) FROM CURRENCY_CODE
UNION ALL
SELECT 'PRODUCT_CATALOG', COUNT(*) FROM PRODUCT_CATALOG
UNION ALL
SELECT 'BRANCH_DIRECTORY', COUNT(*) FROM BRANCH_DIRECTORY
UNION ALL
SELECT 'RELATIONSHIP_MANAGER', COUNT(*) FROM RELATIONSHIP_MANAGER;

-- ============================================
-- FINAL VALIDATION - ALL TABLES
-- ============================================

SELECT '=== COMPLETE DATA LOAD SUMMARY ===' AS STATUS;

SELECT 
    CASE 
        WHEN TABLE_SCHEMA = 'DIGITAL_BANKING' THEN '1_DIGITAL_BANKING'
        WHEN TABLE_SCHEMA = 'CORE_BANKING' THEN '2_CORE_BANKING'
        WHEN TABLE_SCHEMA = 'CREDIT_BUREAU' THEN '3_CREDIT_BUREAU'
        WHEN TABLE_SCHEMA = 'REFERENCE_DATA' THEN '4_REFERENCE_DATA'
    END AS SCHEMA_GROUP,
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT
FROM (
    SELECT 'DIGITAL_BANKING' AS TABLE_SCHEMA, 'DIGITAL_CUSTOMER_PROFILE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIGITAL_BANKING.DIGITAL_CUSTOMER_PROFILE
    UNION ALL SELECT 'DIGITAL_BANKING', 'DIGITAL_SESSION', COUNT(*) FROM DIGITAL_BANKING.DIGITAL_SESSION
    UNION ALL SELECT 'DIGITAL_BANKING', 'DIGITAL_EVENT', COUNT(*) FROM DIGITAL_BANKING.DIGITAL_EVENT
    UNION ALL SELECT 'DIGITAL_BANKING', 'DIGITAL_KYC_DOCUMENT', COUNT(*) FROM DIGITAL_BANKING.DIGITAL_KYC_DOCUMENT
    UNION ALL SELECT 'CORE_BANKING', 'T24_CUSTOMER', COUNT(*) FROM CORE_BANKING.T24_CUSTOMER
    UNION ALL SELECT 'CORE_BANKING', 'T24_ACCOUNT', COUNT(*) FROM CORE_BANKING.T24_ACCOUNT
    UNION ALL SELECT 'CORE_BANKING', 'T24_LOAN', COUNT(*) FROM CORE_BANKING.T24_LOAN
    UNION ALL SELECT 'CORE_BANKING', 'T24_TRANSACTION', COUNT(*) FROM CORE_BANKING.T24_TRANSACTION
    UNION ALL SELECT 'CORE_BANKING', 'T24_PAYMENT_SCHEDULE', COUNT(*) FROM CORE_BANKING.T24_PAYMENT_SCHEDULE
    UNION ALL SELECT 'CORE_BANKING', 'T24_COLLATERAL', COUNT(*) FROM CORE_BANKING.T24_COLLATERAL
    UNION ALL SELECT 'CREDIT_BUREAU', 'CREDIT_SCORE', COUNT(*) FROM CREDIT_BUREAU.CREDIT_SCORE
    UNION ALL SELECT 'CREDIT_BUREAU', 'CREDIT_INQUIRY', COUNT(*) FROM CREDIT_BUREAU.CREDIT_INQUIRY
    UNION ALL SELECT 'CREDIT_BUREAU', 'TRADELINE', COUNT(*) FROM CREDIT_BUREAU.TRADELINE
    UNION ALL SELECT 'CREDIT_BUREAU', 'PUBLIC_RECORD', COUNT(*) FROM CREDIT_BUREAU.PUBLIC_RECORD
    UNION ALL SELECT 'REFERENCE_DATA', 'COUNTRY_CODE', COUNT(*) FROM REFERENCE_DATA.COUNTRY_CODE
    UNION ALL SELECT 'REFERENCE_DATA', 'CURRENCY_CODE', COUNT(*) FROM REFERENCE_DATA.CURRENCY_CODE
    UNION ALL SELECT 'REFERENCE_DATA', 'PRODUCT_CATALOG', COUNT(*) FROM REFERENCE_DATA.PRODUCT_CATALOG
    UNION ALL SELECT 'REFERENCE_DATA', 'BRANCH_DIRECTORY', COUNT(*) FROM REFERENCE_DATA.BRANCH_DIRECTORY
    UNION ALL SELECT 'REFERENCE_DATA', 'RELATIONSHIP_MANAGER', COUNT(*) FROM REFERENCE_DATA.RELATIONSHIP_MANAGER
)
ORDER BY SCHEMA_GROUP, TABLE_NAME;

SELECT '✅ DATA LOAD COMPLETE!' AS STATUS;
