-- ============================================
-- Snowflake Credit Decisioning Platform
-- Step 4: Create Roles and Grant Permissions
-- ============================================

USE ROLE ACCOUNTADMIN;

-- ============================================
-- CREATE CUSTOM ROLES
-- ============================================

CREATE ROLE IF NOT EXISTS CREDIT_OFFICER 
  COMMENT = 'Front-line credit decision makers';

CREATE ROLE IF NOT EXISTS RISK_MANAGER 
  COMMENT = 'Senior risk professionals monitoring portfolio';

CREATE ROLE IF NOT EXISTS COMPLIANCE_OFFICER 
  COMMENT = 'Compliance and audit access';

CREATE ROLE IF NOT EXISTS BRANCH_MANAGER 
  COMMENT = 'Branch-level managers';

CREATE ROLE IF NOT EXISTS DATA_ENGINEER 
  COMMENT = 'Data pipeline developers';

CREATE ROLE IF NOT EXISTS ML_ENGINEER 
  COMMENT = 'ML model developers';

-- ============================================
-- GRANT DATABASE ACCESS
-- ============================================

GRANT USAGE ON DATABASE CREDIT_DECISIONING_DB TO ROLE CREDIT_OFFICER;
GRANT USAGE ON DATABASE CREDIT_DECISIONING_DB TO ROLE RISK_MANAGER;
GRANT USAGE ON DATABASE CREDIT_DECISIONING_DB TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON DATABASE CREDIT_DECISIONING_DB TO ROLE BRANCH_MANAGER;
GRANT USAGE ON DATABASE CREDIT_DECISIONING_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE CREDIT_DECISIONING_DB TO ROLE ML_ENGINEER;

-- ============================================
-- GRANT WAREHOUSE ACCESS
-- ============================================

-- Credit Officers - App and Transactional warehouses
GRANT USAGE ON WAREHOUSE APP_WH TO ROLE CREDIT_OFFICER;
GRANT USAGE ON WAREHOUSE TRANSACTIONAL_WH TO ROLE CREDIT_OFFICER;

-- Risk Managers - App warehouse
GRANT USAGE ON WAREHOUSE APP_WH TO ROLE RISK_MANAGER;

-- Compliance Officers - App warehouse
GRANT USAGE ON WAREHOUSE APP_WH TO ROLE COMPLIANCE_OFFICER;

-- Branch Managers - App warehouse
GRANT USAGE ON WAREHOUSE APP_WH TO ROLE BRANCH_MANAGER;

-- Data Engineers - ETL warehouse
GRANT USAGE ON WAREHOUSE ETL_WH TO ROLE DATA_ENGINEER;
GRANT OPERATE ON WAREHOUSE ETL_WH TO ROLE DATA_ENGINEER;

-- ML Engineers - ML warehouse
GRANT USAGE ON WAREHOUSE ML_WH TO ROLE ML_ENGINEER;
GRANT OPERATE ON WAREHOUSE ML_WH TO ROLE ML_ENGINEER;

-- ============================================
-- GRANT SCHEMA ACCESS - CREDIT OFFICER
-- ============================================

GRANT USAGE ON SCHEMA ANALYTICS_ZONE.CUSTOMER_360 TO ROLE CREDIT_OFFICER;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_ZONE.CUSTOMER_360 TO ROLE CREDIT_OFFICER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_ZONE.CUSTOMER_360 TO ROLE CREDIT_OFFICER;

GRANT USAGE ON SCHEMA APP_ZONE.TRANSACTIONAL TO ROLE CREDIT_OFFICER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA APP_ZONE.TRANSACTIONAL TO ROLE CREDIT_OFFICER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA APP_ZONE.TRANSACTIONAL TO ROLE CREDIT_OFFICER;

GRANT USAGE ON SCHEMA APP_ZONE.CORTEX TO ROLE CREDIT_OFFICER;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA APP_ZONE.CORTEX TO ROLE CREDIT_OFFICER;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA APP_ZONE.CORTEX TO ROLE CREDIT_OFFICER;

GRANT USAGE ON SCHEMA ML_ZONE.INFERENCE TO ROLE CREDIT_OFFICER;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA ML_ZONE.INFERENCE TO ROLE CREDIT_OFFICER;

-- ============================================
-- GRANT SCHEMA ACCESS - RISK MANAGER
-- ============================================

GRANT USAGE ON ALL SCHEMAS IN DATABASE CREDIT_DECISIONING_DB TO ROLE RISK_MANAGER;
GRANT SELECT ON ALL TABLES IN DATABASE CREDIT_DECISIONING_DB TO ROLE RISK_MANAGER;
GRANT SELECT ON ALL VIEWS IN DATABASE CREDIT_DECISIONING_DB TO ROLE RISK_MANAGER;
GRANT SELECT ON FUTURE TABLES IN DATABASE CREDIT_DECISIONING_DB TO ROLE RISK_MANAGER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE CREDIT_DECISIONING_DB TO ROLE RISK_MANAGER;

-- ============================================
-- GRANT SCHEMA ACCESS - COMPLIANCE OFFICER
-- ============================================

GRANT USAGE ON SCHEMA GOVERNANCE.AUDIT TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE.AUDIT TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE.AUDIT TO ROLE COMPLIANCE_OFFICER;

-- Access to Snowflake's ACCOUNT_USAGE for audit
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE COMPLIANCE_OFFICER;

-- ============================================
-- GRANT SCHEMA ACCESS - DATA ENGINEER
-- ============================================

GRANT USAGE ON ALL SCHEMAS IN DATABASE CREDIT_DECISIONING_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA RAW_ZONE TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CURATED_ZONE TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ANALYTICS_ZONE TO ROLE DATA_ENGINEER;

-- ============================================
-- GRANT SCHEMA ACCESS - ML ENGINEER
-- ============================================

GRANT USAGE ON SCHEMA ANALYTICS_ZONE.FEATURE_STORE TO ROLE ML_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ANALYTICS_ZONE.FEATURE_STORE TO ROLE ML_ENGINEER;

GRANT USAGE ON ALL SCHEMAS IN SCHEMA ML_ZONE TO ROLE ML_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ML_ZONE.TRAINING TO ROLE ML_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ML_ZONE.MODELS TO ROLE ML_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ML_ZONE.INFERENCE TO ROLE ML_ENGINEER;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA ML_ZONE.INFERENCE TO ROLE ML_ENGINEER;

-- ============================================
-- ROLE HIERARCHY
-- ============================================

GRANT ROLE CREDIT_OFFICER TO ROLE BRANCH_MANAGER;
GRANT ROLE BRANCH_MANAGER TO ROLE RISK_MANAGER;
GRANT ROLE RISK_MANAGER TO ROLE SYSADMIN;
GRANT ROLE COMPLIANCE_OFFICER TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE ML_ENGINEER TO ROLE SYSADMIN;

SELECT 'All roles created and permissions granted successfully' AS STATUS;
