-- ============================================
-- Snowflake Credit Decisioning Platform
-- ETL: Customer 360 Unified View
-- Creates unified customer profile from all sources
-- ============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CREDIT_DECISIONING_DB;
USE WAREHOUSE COMPUTE_WH;

-- ============================================
-- CUSTOMER 360 UNIFIED VIEW
-- ============================================
-- Single source of truth for customer data from all systems

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_CUSTOMER_360.CUSTOMER_360_UNIFIED
  TARGET_LAG = '5 minutes'
  WAREHOUSE = COMPUTE_WH
  COMMENT = 'Unified Customer 360 view from all data sources'
AS
SELECT 
    -- Customer Identifiers
    c.CUSTOMER_ID,
    c.MNEMONIC,
    c.SHORT_NAME,
    c.NAME_1 AS FIRST_NAME,
    c.NAME_2 AS LAST_NAME,
    CONCAT(c.NAME_1, ' ', COALESCE(c.NAME_2, '')) AS FULL_NAME,
    
    -- Demographics
    c.GENDER,
    c.DATE_OF_BIRTH,
    DATEDIFF('YEAR', c.DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    c.MARITAL_STATUS,
    c.NATIONALITY,
    c.RESIDENCE,
    
    -- Business Information
    c.SECTOR,
    c.INDUSTRY,
    c.TARGET_MARKET,
    
    -- Customer Status
    c.CUSTOMER_STATUS,
    c.CUSTOMER_SINCE,
    DATEDIFF('MONTH', c.CUSTOMER_SINCE, CURRENT_DATE()) AS RELATIONSHIP_MONTHS,
    c.KYC_STATUS,
    c.KYC_LAST_REVIEW,
    c.RISK_CATEGORY,
    
    -- Relationship Management
    c.RELATIONSHIP_MANAGER,
    c.BRANCH_CODE,
    
    -- ============================================
    -- FINANCIAL SUMMARY
    -- ============================================
    acc.TOTAL_ACCOUNTS,
    acc.TOTAL_BALANCE,
    acc.AVG_BALANCE,
    acc.TOTAL_AVAILABLE_LIMIT,
    acc.ACTIVE_ACCOUNTS,
    
    loan.TOTAL_LOANS,
    loan.ACTIVE_LOANS,
    loan.TOTAL_OUTSTANDING,
    loan.TOTAL_MONTHLY_PAYMENT,
    loan.DELINQUENT_LOANS,
    loan.TOTAL_ARREARS,
    
    -- ============================================
    -- CREDIT BUREAU DATA
    -- ============================================
    cb.CREDIT_SCORE,
    cb.CREDIT_UTILIZATION,
    cb.TOTAL_TRADELINES,
    cb.OPEN_TRADELINES,
    cb.DELINQUENT_TRADELINES,
    cb.PUBLIC_RECORDS,
    cb.LATEST_INQUIRY_DATE,
    
    -- ============================================
    -- DIGITAL BEHAVIOR
    -- ============================================
    dig.DIGITAL_ID,
    dig.EMAIL,
    dig.MOBILE_NUMBER,
    dig.USERNAME,
    dig.REGISTRATION_DATE AS DIGITAL_REGISTRATION_DATE,
    dig.LAST_LOGIN,
    dig.LOGIN_COUNT,
    dig.SESSION_COUNT_30D,
    dig.AVG_SESSION_DURATION,
    dig.MFA_ENABLED,
    dig.BIOMETRIC_ENABLED,
    dig.EKYC_STATUS,
    
    -- ============================================
    -- COMPUTED METRICS
    -- ============================================
    CASE 
        WHEN loan.TOTAL_MONTHLY_PAYMENT > 0 AND acc.ESTIMATED_MONTHLY_INCOME > 0
        THEN loan.TOTAL_MONTHLY_PAYMENT / acc.ESTIMATED_MONTHLY_INCOME
        ELSE 0
    END AS DEBT_TO_INCOME_RATIO,
    
    CASE 
        WHEN acc.TOTAL_AVAILABLE_LIMIT > 0
        THEN acc.TOTAL_BALANCE / acc.TOTAL_AVAILABLE_LIMIT
        ELSE 0
    END AS CREDIT_UTILIZATION_RATIO,
    
    CASE 
        WHEN cb.CREDIT_SCORE >= 750 THEN 'EXCELLENT'
        WHEN cb.CREDIT_SCORE >= 700 THEN 'GOOD'
        WHEN cb.CREDIT_SCORE >= 650 THEN 'FAIR'
        WHEN cb.CREDIT_SCORE >= 600 THEN 'POOR'
        ELSE 'VERY_POOR'
    END AS CREDIT_RATING,
    
    -- Timestamps
    CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM CORE_BANKING.T24_CUSTOMER c

-- Account Summary
LEFT JOIN (
    SELECT 
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_ACCOUNTS,
        SUM(WORKING_BALANCE) AS TOTAL_BALANCE,
        AVG(WORKING_BALANCE) AS AVG_BALANCE,
        SUM(AVAILABLE_LIMIT) AS TOTAL_AVAILABLE_LIMIT,
        SUM(CASE WHEN ACCOUNT_STATUS = 'ACTIVE' THEN 1 ELSE 0 END) AS ACTIVE_ACCOUNTS,
        -- Estimate monthly income (simplified - would use actual income verification)
        AVG(WORKING_BALANCE) * 0.1 AS ESTIMATED_MONTHLY_INCOME
    FROM CORE_BANKING.T24_ACCOUNT
    GROUP BY CUSTOMER_ID
) acc ON c.CUSTOMER_ID = acc.CUSTOMER_ID

-- Loan Summary
LEFT JOIN (
    SELECT 
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_LOANS,
        SUM(CASE WHEN LOAN_STATUS IN ('ACTIVE', 'PAST_DUE') THEN 1 ELSE 0 END) AS ACTIVE_LOANS,
        SUM(OUTSTANDING_PRINCIPAL) AS TOTAL_OUTSTANDING,
        SUM(MONTHLY_PAYMENT) AS TOTAL_MONTHLY_PAYMENT,
        SUM(CASE WHEN DAYS_PAST_DUE > 0 THEN 1 ELSE 0 END) AS DELINQUENT_LOANS,
        SUM(ARREARS_AMOUNT) AS TOTAL_ARREARS
    FROM CORE_BANKING.T24_LOAN
    GROUP BY CUSTOMER_ID
) loan ON c.CUSTOMER_ID = loan.CUSTOMER_ID

-- Credit Bureau Summary
LEFT JOIN (
    SELECT 
        cs.CUSTOMER_ID,
        cs.SCORE AS CREDIT_SCORE,
        cs.CREDIT_UTILIZATION,
        COUNT(DISTINCT tl.TRADELINE_ID) AS TOTAL_TRADELINES,
        SUM(CASE WHEN tl.ACCOUNT_STATUS = 'OPEN' THEN 1 ELSE 0 END) AS OPEN_TRADELINES,
        SUM(CASE WHEN tl.PAYMENT_STATUS IN ('PAST_DUE', 'DELINQUENT', 'DEFAULT') THEN 1 ELSE 0 END) AS DELINQUENT_TRADELINES,
        COUNT(DISTINCT pr.RECORD_ID) AS PUBLIC_RECORDS,
        MAX(ci.INQUIRY_DATE) AS LATEST_INQUIRY_DATE
    FROM CREDIT_BUREAU.CREDIT_SCORE cs
    LEFT JOIN CREDIT_BUREAU.TRADELINE tl ON cs.CUSTOMER_ID = tl.CUSTOMER_ID
    LEFT JOIN CREDIT_BUREAU.PUBLIC_RECORD pr ON cs.CUSTOMER_ID = pr.CUSTOMER_ID
    LEFT JOIN CREDIT_BUREAU.CREDIT_INQUIRY ci ON cs.CUSTOMER_ID = ci.CUSTOMER_ID
    GROUP BY cs.CUSTOMER_ID, cs.SCORE, cs.CREDIT_UTILIZATION
) cb ON c.CUSTOMER_ID = cb.CUSTOMER_ID

-- Digital Profile
LEFT JOIN (
    SELECT 
        dcp.CUSTOMER_ID,
        dcp.DIGITAL_ID,
        dcp.EMAIL,
        dcp.MOBILE_NUMBER,
        dcp.USERNAME,
        dcp.REGISTRATION_DATE,
        dcp.LAST_LOGIN,
        dcp.LOGIN_COUNT,
        dcp.MFA_ENABLED,
        dcp.BIOMETRIC_ENABLED,
        dcp.EKYC_STATUS,
        COUNT(DISTINCT ds.SESSION_ID) AS SESSION_COUNT_30D,
        AVG(ds.DURATION_SECONDS) AS AVG_SESSION_DURATION
    FROM DIGITAL_BANKING.DIGITAL_CUSTOMER_PROFILE dcp
    LEFT JOIN DIGITAL_BANKING.DIGITAL_SESSION ds 
        ON dcp.DIGITAL_ID = ds.DIGITAL_ID
        AND ds.SESSION_START >= DATEADD('DAY', -30, CURRENT_DATE())
    GROUP BY dcp.CUSTOMER_ID, dcp.DIGITAL_ID, dcp.EMAIL, dcp.MOBILE_NUMBER,
             dcp.USERNAME, dcp.REGISTRATION_DATE, dcp.LAST_LOGIN, dcp.LOGIN_COUNT,
             dcp.MFA_ENABLED, dcp.BIOMETRIC_ENABLED, dcp.EKYC_STATUS
) dig ON c.CUSTOMER_ID = dig.CUSTOMER_ID;

-- ============================================
-- CUSTOMER FINANCIAL SUMMARY
-- ============================================

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_CUSTOMER_360.CUSTOMER_FINANCIAL_SUMMARY
  TARGET_LAG = '5 minutes'
  WAREHOUSE = COMPUTE_WH
  COMMENT = 'Financial summary for each customer'
AS
SELECT 
    c.CUSTOMER_ID,
    
    -- Account Summary
    COUNT(DISTINCT a.ACCOUNT_ID) AS ACCOUNT_COUNT,
    SUM(a.WORKING_BALANCE) AS TOTAL_DEPOSITS,
    SUM(a.AVAILABLE_LIMIT) AS TOTAL_CREDIT_LIMIT,
    AVG(a.WORKING_BALANCE) AS AVG_ACCOUNT_BALANCE,
    
    -- Loan Summary
    COUNT(DISTINCT l.LOAN_ID) AS LOAN_COUNT,
    SUM(l.PRINCIPAL_AMOUNT) AS TOTAL_LOAN_AMOUNT,
    SUM(l.OUTSTANDING_PRINCIPAL) AS TOTAL_OUTSTANDING,
    SUM(l.MONTHLY_PAYMENT) AS TOTAL_MONTHLY_PAYMENT,
    AVG(l.INTEREST_RATE) AS AVG_INTEREST_RATE,
    
    -- Transaction Summary (30 days)
    COUNT(DISTINCT t.TRANSACTION_ID) AS TXN_COUNT_30D,
    SUM(ABS(t.AMOUNT)) AS TXN_AMOUNT_30D,
    
    -- Risk Indicators
    SUM(CASE WHEN l.DAYS_PAST_DUE > 0 THEN 1 ELSE 0 END) AS DELINQUENT_LOANS,
    SUM(l.ARREARS_AMOUNT) AS TOTAL_ARREARS,
    MAX(l.DAYS_PAST_DUE) AS MAX_DAYS_PAST_DUE,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM CORE_BANKING.T24_CUSTOMER c
LEFT JOIN CORE_BANKING.T24_ACCOUNT a ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN CORE_BANKING.T24_LOAN l ON c.CUSTOMER_ID = l.CUSTOMER_ID
LEFT JOIN CORE_BANKING.T24_TRANSACTION t 
    ON c.CUSTOMER_ID = t.CUSTOMER_ID
    AND t.VALUE_DATE >= DATEADD('DAY', -30, CURRENT_DATE())
GROUP BY c.CUSTOMER_ID;

-- Grant permissions
GRANT SELECT ON DYNAMIC TABLE ANALYTICS_CUSTOMER_360.CUSTOMER_360_UNIFIED TO ROLE SYSADMIN;
GRANT SELECT ON DYNAMIC TABLE ANALYTICS_CUSTOMER_360.CUSTOMER_FINANCIAL_SUMMARY TO ROLE SYSADMIN;

-- Verify creation
SELECT 
    'Customer 360 Created' AS STATUS,
    COUNT(*) AS CUSTOMER_COUNT
FROM ANALYTICS_CUSTOMER_360.CUSTOMER_360_UNIFIED;

SELECT 'Customer 360 Dynamic Tables created successfully!' AS STATUS;
