-- ============================================
-- Snowflake Credit Decisioning Platform
-- ETL: Portfolio Analytics Dynamic Tables
-- Creates portfolio-level risk metrics and aggregations
-- ============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CREDIT_DECISIONING_DB;
USE WAREHOUSE COMPUTE_WH;

-- ============================================
-- PORTFOLIO SUMMARY
-- ============================================
-- High-level portfolio metrics

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_RISK_ANALYTICS.PORTFOLIO_SUMMARY
  TARGET_LAG = '15 minutes'
  WAREHOUSE = COMPUTE_WH
  COMMENT = 'Portfolio-level summary metrics'
AS
SELECT 
    CURRENT_DATE() AS REPORT_DATE,
    
    -- Customer Metrics
    COUNT(DISTINCT c.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    COUNT(DISTINCT CASE WHEN c.CUSTOMER_STATUS = 'ACTIVE' THEN c.CUSTOMER_ID END) AS ACTIVE_CUSTOMERS,
    
    -- Account Metrics
    COUNT(DISTINCT a.ACCOUNT_ID) AS TOTAL_ACCOUNTS,
    SUM(a.WORKING_BALANCE) AS TOTAL_DEPOSITS,
    SUM(a.AVAILABLE_LIMIT) AS TOTAL_CREDIT_LIMIT,
    AVG(a.WORKING_BALANCE) AS AVG_ACCOUNT_BALANCE,
    
    -- Loan Metrics
    COUNT(DISTINCT l.LOAN_ID) AS TOTAL_LOANS,
    COUNT(DISTINCT CASE WHEN l.LOAN_STATUS = 'ACTIVE' THEN l.LOAN_ID END) AS ACTIVE_LOANS,
    SUM(l.PRINCIPAL_AMOUNT) AS TOTAL_LOAN_PORTFOLIO,
    SUM(l.OUTSTANDING_PRINCIPAL) AS TOTAL_OUTSTANDING,
    SUM(l.MONTHLY_PAYMENT) AS TOTAL_MONTHLY_PAYMENT,
    AVG(l.INTEREST_RATE) AS AVG_INTEREST_RATE,
    
    -- Risk Metrics
    COUNT(DISTINCT CASE WHEN l.DAYS_PAST_DUE > 0 THEN l.LOAN_ID END) AS DELINQUENT_LOANS,
    SUM(l.ARREARS_AMOUNT) AS TOTAL_ARREARS,
    CASE 
        WHEN COUNT(DISTINCT l.LOAN_ID) > 0
        THEN COUNT(DISTINCT CASE WHEN l.DAYS_PAST_DUE > 0 THEN l.LOAN_ID END)::FLOAT / COUNT(DISTINCT l.LOAN_ID) * 100
        ELSE 0
    END AS DELINQUENCY_RATE,
    
    CASE 
        WHEN SUM(l.OUTSTANDING_PRINCIPAL) > 0
        THEN SUM(l.ARREARS_AMOUNT) / SUM(l.OUTSTANDING_PRINCIPAL) * 100
        ELSE 0
    END AS ARREARS_RATE,
    
    -- Credit Score Distribution
    AVG(cb.CREDIT_SCORE) AS AVG_CREDIT_SCORE,
    MIN(cb.CREDIT_SCORE) AS MIN_CREDIT_SCORE,
    MAX(cb.CREDIT_SCORE) AS MAX_CREDIT_SCORE,
    
    COUNT(DISTINCT CASE WHEN cb.CREDIT_SCORE >= 750 THEN c.CUSTOMER_ID END) AS EXCELLENT_CREDIT_COUNT,
    COUNT(DISTINCT CASE WHEN cb.CREDIT_SCORE BETWEEN 700 AND 749 THEN c.CUSTOMER_ID END) AS GOOD_CREDIT_COUNT,
    COUNT(DISTINCT CASE WHEN cb.CREDIT_SCORE BETWEEN 650 AND 699 THEN c.CUSTOMER_ID END) AS FAIR_CREDIT_COUNT,
    COUNT(DISTINCT CASE WHEN cb.CREDIT_SCORE < 650 THEN c.CUSTOMER_ID END) AS POOR_CREDIT_COUNT,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM CORE_BANKING.T24_CUSTOMER c
LEFT JOIN CORE_BANKING.T24_ACCOUNT a ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN CORE_BANKING.T24_LOAN l ON c.CUSTOMER_ID = l.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, SCORE AS CREDIT_SCORE
    FROM CREDIT_BUREAU.CREDIT_SCORE
) cb ON c.CUSTOMER_ID = cb.CUSTOMER_ID
GROUP BY CURRENT_DATE();

-- ============================================
-- DELINQUENCY COHORTS
-- ============================================
-- Track loans by days past due buckets

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_RISK_ANALYTICS.DELINQUENCY_COHORTS
  TARGET_LAG = '15 minutes'
  WAREHOUSE = COMPUTE_WH
  COMMENT = 'Delinquency cohorts by days past due'
AS
SELECT 
    CURRENT_DATE() AS REPORT_DATE,
    
    CASE 
        WHEN DAYS_PAST_DUE = 0 THEN 'CURRENT'
        WHEN DAYS_PAST_DUE BETWEEN 1 AND 30 THEN '1-30 DAYS'
        WHEN DAYS_PAST_DUE BETWEEN 31 AND 60 THEN '31-60 DAYS'
        WHEN DAYS_PAST_DUE BETWEEN 61 AND 90 THEN '61-90 DAYS'
        WHEN DAYS_PAST_DUE > 90 THEN '90+ DAYS'
        ELSE 'UNKNOWN'
    END AS DELINQUENCY_BUCKET,
    
    COUNT(*) AS LOAN_COUNT,
    SUM(OUTSTANDING_PRINCIPAL) AS TOTAL_OUTSTANDING,
    SUM(ARREARS_AMOUNT) AS TOTAL_ARREARS,
    AVG(DAYS_PAST_DUE) AS AVG_DAYS_PAST_DUE,
    MAX(DAYS_PAST_DUE) AS MAX_DAYS_PAST_DUE,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM CORE_BANKING.T24_LOAN
WHERE LOAN_STATUS IN ('ACTIVE', 'PAST_DUE')
GROUP BY 
    CASE 
        WHEN DAYS_PAST_DUE = 0 THEN 'CURRENT'
        WHEN DAYS_PAST_DUE BETWEEN 1 AND 30 THEN '1-30 DAYS'
        WHEN DAYS_PAST_DUE BETWEEN 31 AND 60 THEN '31-60 DAYS'
        WHEN DAYS_PAST_DUE BETWEEN 61 AND 90 THEN '61-90 DAYS'
        WHEN DAYS_PAST_DUE > 90 THEN '90+ DAYS'
        ELSE 'UNKNOWN'
    END;

-- ============================================
-- RISK SEGMENTS
-- ============================================
-- Segment customers by risk level

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_RISK_ANALYTICS.RISK_SEGMENTS
  TARGET_LAG = '15 minutes'
  WAREHOUSE = COMPUTE_WH
  COMMENT = 'Customer risk segmentation'
AS
SELECT 
    CURRENT_DATE() AS REPORT_DATE,
    
    CASE 
        WHEN cb.CREDIT_SCORE >= 750 AND COALESCE(l.DELINQUENT_LOANS, 0) = 0 THEN 'LOW_RISK'
        WHEN cb.CREDIT_SCORE >= 700 AND COALESCE(l.DELINQUENT_LOANS, 0) = 0 THEN 'MEDIUM_LOW_RISK'
        WHEN cb.CREDIT_SCORE >= 650 OR COALESCE(l.DELINQUENT_LOANS, 0) > 0 THEN 'MEDIUM_RISK'
        WHEN cb.CREDIT_SCORE >= 600 OR COALESCE(l.DELINQUENT_LOANS, 0) > 1 THEN 'MEDIUM_HIGH_RISK'
        ELSE 'HIGH_RISK'
    END AS RISK_SEGMENT,
    
    COUNT(DISTINCT c.CUSTOMER_ID) AS CUSTOMER_COUNT,
    COUNT(DISTINCT loan.LOAN_ID) AS LOAN_COUNT,
    SUM(COALESCE(loan.OUTSTANDING_PRINCIPAL, 0)) AS TOTAL_OUTSTANDING,
    AVG(cb.CREDIT_SCORE) AS AVG_CREDIT_SCORE,
    SUM(COALESCE(l.DELINQUENT_LOANS, 0)) AS TOTAL_DELINQUENT_LOANS,
    
    CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM CORE_BANKING.T24_CUSTOMER c
LEFT JOIN (
    SELECT CUSTOMER_ID, SCORE AS CREDIT_SCORE
    FROM CREDIT_BUREAU.CREDIT_SCORE
) cb ON c.CUSTOMER_ID = cb.CUSTOMER_ID
LEFT JOIN (
    SELECT 
        CUSTOMER_ID,
        COUNT(*) AS DELINQUENT_LOANS
    FROM CORE_BANKING.T24_LOAN
    WHERE DAYS_PAST_DUE > 0
    GROUP BY CUSTOMER_ID
) l ON c.CUSTOMER_ID = l.CUSTOMER_ID
LEFT JOIN CORE_BANKING.T24_LOAN loan ON c.CUSTOMER_ID = loan.CUSTOMER_ID
GROUP BY 
    CASE 
        WHEN cb.CREDIT_SCORE >= 750 AND COALESCE(l.DELINQUENT_LOANS, 0) = 0 THEN 'LOW_RISK'
        WHEN cb.CREDIT_SCORE >= 700 AND COALESCE(l.DELINQUENT_LOANS, 0) = 0 THEN 'MEDIUM_LOW_RISK'
        WHEN cb.CREDIT_SCORE >= 650 OR COALESCE(l.DELINQUENT_LOANS, 0) > 0 THEN 'MEDIUM_RISK'
        WHEN cb.CREDIT_SCORE >= 600 OR COALESCE(l.DELINQUENT_LOANS, 0) > 1 THEN 'MEDIUM_HIGH_RISK'
        ELSE 'HIGH_RISK'
    END;

-- ============================================
-- EARLY WARNING ALERTS
-- ============================================
-- Identify customers showing early warning signs

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_RISK_ANALYTICS.EARLY_WARNING_ALERTS
  TARGET_LAG = '15 minutes'
  WAREHOUSE = COMPUTE_WH
  COMMENT = 'Early warning indicators for at-risk customers'
AS
SELECT 
    c.CUSTOMER_ID,
    c.NAME_1 || ' ' || COALESCE(c.NAME_2, '') AS CUSTOMER_NAME,
    c.CUSTOMER_STATUS,
    
    -- Warning Indicators
    CASE WHEN l.DAYS_PAST_DUE BETWEEN 1 AND 30 THEN TRUE ELSE FALSE END AS EARLY_DELINQUENCY,
    CASE WHEN cb.CREDIT_SCORE < 600 THEN TRUE ELSE FALSE END AS LOW_CREDIT_SCORE,
    CASE WHEN acc.UTILIZATION_RATIO > 0.8 THEN TRUE ELSE FALSE END AS HIGH_UTILIZATION,
    CASE WHEN txn.TXN_COUNT_30D < 2 THEN TRUE ELSE FALSE END AS LOW_ACTIVITY,
    CASE WHEN dig.DAYS_SINCE_LAST_LOGIN > 90 THEN TRUE ELSE FALSE END AS INACTIVE_DIGITAL,
    
    -- Risk Score
    CASE 
        WHEN l.DAYS_PAST_DUE BETWEEN 1 AND 30 THEN 1 ELSE 0
    END +
    CASE WHEN cb.CREDIT_SCORE < 600 THEN 1 ELSE 0 END +
    CASE WHEN acc.UTILIZATION_RATIO > 0.8 THEN 1 ELSE 0 END +
    CASE WHEN txn.TXN_COUNT_30D < 2 THEN 1 ELSE 0 END +
    CASE WHEN dig.DAYS_SINCE_LAST_LOGIN > 90 THEN 1 ELSE 0 END AS RISK_SCORE,
    
    -- Details
    l.DAYS_PAST_DUE,
    cb.CREDIT_SCORE,
    acc.UTILIZATION_RATIO,
    txn.TXN_COUNT_30D,
    dig.DAYS_SINCE_LAST_LOGIN,
    
    CURRENT_TIMESTAMP() AS ALERT_DATE

FROM CORE_BANKING.T24_CUSTOMER c
LEFT JOIN (
    SELECT 
        CUSTOMER_ID,
        MAX(DAYS_PAST_DUE) AS DAYS_PAST_DUE
    FROM CORE_BANKING.T24_LOAN
    WHERE LOAN_STATUS IN ('ACTIVE', 'PAST_DUE')
    GROUP BY CUSTOMER_ID
) l ON c.CUSTOMER_ID = l.CUSTOMER_ID
LEFT JOIN (
    SELECT CUSTOMER_ID, SCORE AS CREDIT_SCORE
    FROM CREDIT_BUREAU.CREDIT_SCORE
) cb ON c.CUSTOMER_ID = cb.CUSTOMER_ID
LEFT JOIN (
    SELECT 
        CUSTOMER_ID,
        CASE 
            WHEN SUM(AVAILABLE_LIMIT) > 0
            THEN SUM(WORKING_BALANCE) / SUM(AVAILABLE_LIMIT)
            ELSE 0
        END AS UTILIZATION_RATIO
    FROM CORE_BANKING.T24_ACCOUNT
    GROUP BY CUSTOMER_ID
) acc ON c.CUSTOMER_ID = acc.CUSTOMER_ID
LEFT JOIN (
    SELECT 
        CUSTOMER_ID,
        COUNT(*) AS TXN_COUNT_30D
    FROM CORE_BANKING.T24_TRANSACTION
    WHERE VALUE_DATE >= DATEADD('DAY', -30, CURRENT_DATE())
    GROUP BY CUSTOMER_ID
) txn ON c.CUSTOMER_ID = txn.CUSTOMER_ID
LEFT JOIN (
    SELECT 
        dcp.CUSTOMER_ID,
        DATEDIFF('DAY', dcp.LAST_LOGIN, CURRENT_DATE()) AS DAYS_SINCE_LAST_LOGIN
    FROM DIGITAL_BANKING.DIGITAL_CUSTOMER_PROFILE dcp
) dig ON c.CUSTOMER_ID = dig.CUSTOMER_ID
WHERE 
    (l.DAYS_PAST_DUE BETWEEN 1 AND 30)
    OR cb.CREDIT_SCORE < 600
    OR acc.UTILIZATION_RATIO > 0.8
    OR txn.TXN_COUNT_30D < 2
    OR dig.DAYS_SINCE_LAST_LOGIN > 90;

-- Grant permissions
GRANT SELECT ON DYNAMIC TABLE ANALYTICS_RISK_ANALYTICS.PORTFOLIO_SUMMARY TO ROLE SYSADMIN;
GRANT SELECT ON DYNAMIC TABLE ANALYTICS_RISK_ANALYTICS.DELINQUENCY_COHORTS TO ROLE SYSADMIN;
GRANT SELECT ON DYNAMIC TABLE ANALYTICS_RISK_ANALYTICS.RISK_SEGMENTS TO ROLE SYSADMIN;
GRANT SELECT ON DYNAMIC TABLE ANALYTICS_RISK_ANALYTICS.EARLY_WARNING_ALERTS TO ROLE SYSADMIN;

-- Verify creation
SELECT 'Portfolio Analytics Created' AS STATUS,
       (SELECT COUNT(*) FROM ANALYTICS_RISK_ANALYTICS.PORTFOLIO_SUMMARY) AS PORTFOLIO_SUMMARY_ROWS,
       (SELECT COUNT(*) FROM ANALYTICS_RISK_ANALYTICS.DELINQUENCY_COHORTS) AS DELINQUENCY_COHORT_ROWS,
       (SELECT COUNT(*) FROM ANALYTICS_RISK_ANALYTICS.RISK_SEGMENTS) AS RISK_SEGMENT_ROWS,
       (SELECT COUNT(*) FROM ANALYTICS_RISK_ANALYTICS.EARLY_WARNING_ALERTS) AS ALERT_ROWS;

SELECT 'Portfolio Analytics Dynamic Tables created successfully!' AS STATUS;
